{{- range .Values.clusters }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: policies 
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/tommeramber/acm-sme.git
      revision: HEAD
      directories:
      - path: everything-in-argo/policies/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    spec:
      project: default
      source:
        repoURL: https://github.com/tommeramber/acm-sme.git
        targetRevision: HEAD
        helm:
          valueFiles:
          - {{ .name }}-values.yaml
      destination:
        server: {{ .url }}
      syncPolicy: {}
      # Operators
      #        automated: 
      #          prune: true
      #        syncOptions:
      #        - Replace=true
{{- end }}
