{{- range .Values.clusters }}
{{- if .required }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .name }}-policies 
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/tommeramber/acm-sme.git
      revision: HEAD
      directories:
      - path: everything-in-argo/policies/*
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      # https://stackoverflow.com/questions/55673385/helm-upgrade-fails-with-function-x-not-defined
      name: {{`'{{path.basename}}'`}} 
    spec:
      project: default
      source:
        repoURL: https://github.com/tommeramber/acm-sme.git
        targetRevision: HEAD
        path: {{`'{{path}}'`}}
        helm:
          valueFiles:
          - {{ .name }}-values.yaml
      destination:
        server: {{ .url }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
{{- end }}
{{- end }}
