apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: mycluster
  labels:
    name: mycluster
    cloud: auto-detect
    vendor: auto-detect
    env: dev
    cluster.open-cluster-management.io/clusterset: default
  annotations: {}
spec:
  hubAcceptsClient: true
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: mycluster
  namespace: mycluster
spec:
  clusterName: mycluster
  clusterNamespace: mycluster
  clusterLabels:
    name: mycluster
    cloud: auto-detect
    vendor: auto-detect
    env: dev
    cluster.open-cluster-management.io/clusterset: default
  applicationManager:
    enabled: true
    argocdCluster: false
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
