{{- if .Values.required }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-oauth-htpasswd
  namespace: gitops-demo
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-oauth
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: OAuth
                metadata:
                  name: cluster
                spec:
                  identityProviders:
                  {{- if .Values.htpasswd }}
                  - name: htpasswd 
                    mappingMethod: claim 
                    type: HTPasswd
                    htpasswd:
                      fileData:
                        name: {{ .Values.htpasswdSecretName }}
                   {{- end }}
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-oauth-secret
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                {{- if .Values.htpasswd }}
                apiVersion: v1
                kind: Secret
                metadata:
                  name: {{ .Values.htpasswdSecretName }}
                  namespace: openshift-config
                  annotations:
                    argocd.argoproj.io/sync-options: Prune=false
                    argocd.argoproj.io/compare-options: IgnoreExtraneous
                type: Opaque 
                data:
                  htpasswd: {{ .Files.Get "files/htpasswd" | b64enc | quote }}
                {{- end }}
{{- end }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-oauth-htpasswd
  namespace: gitops-demo
placementRef:
  name: placement-policy-oauth-htpasswd
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-oauth-htpasswd
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-oauth-htpasswd
  namespace: gitops-demo
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: local-cluster
        operator: In
        values:
          - 'true'
