apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc  
  project: default
  source:
    path: everything-in-argo/applicationsets
    repoURL: https://github.com/tommeramber/acm-sme.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
