---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-always-pull-images
  namespace: acm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/controls: SC-28 (1) Cryptographic Protection
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: prevent-new-pod-without-always-pull-image
        spec:
          remediationAction: enforce
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: kyverno.io/v1
                kind: ClusterPolicy
                metadata:
                  name: always-pull-images
                  annotations:
                    policies.kyverno.io/title: Always Pull Images
                    policies.kyverno.io/category: Sample
                    policies.kyverno.io/severity: medium
                    policies.kyverno.io/subject: Pod
                    policies.kyverno.io/description: >-
                      By default, images that have already been pulled can be accessed by other
                      Pods without re-pulling them if the name and tag are known. In multi-tenant scenarios,
                      this may be undesirable. This policy mutates all incoming Pods to set their
                      imagePullPolicy to Always. An alternative to the Kubernetes admission controller
                      AlwaysPullImages.      
                spec:
                  rules:
                  - name: always-pull-images
                    match:
                      resources:
                        kinds:
                        - Pod
                    mutate:
                      patchStrategicMerge:
                        spec:
                          containers:
                          - (name): "?*"
                            imagePullPolicy: Always
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-always-pull-images
  namespace: acm-policies
placementRef:
  name: placement-policy-always-pull-images
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-always-pull-images
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-always-pull-images
  namespace: acm-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: {{.Values.clusters.key}}
        operator: In
        values: 
        - {{.Values.clusters.value | quote}}
